### ISSUE TITLE
Material Count Display Goes Beyond Display Area

### ISSUE THREAD

**Issue by Piskieee** [Guillaume-Docquier/guillaume-docquier.github.io#43]
With the addition of Stonemasonry recipes the current numerical visual is no longer adequate due to the sheer number of materials. Needs to be adjusted to display more clearly.

Suggestions:
- Shift the number below the asset picture instead of overlaid and add a buffer of a few (estimate 3) pixels to each side of the component to space it horizontally more. 
- Adding punctuation based on the users browser language to help visualize numbers better as components rise to 7 digits in larger Stonemasonry recipes

**Comment by Guillaume-Docquier** [comment]
I tweaked the display today before seeing your suggestions.
When the quantity goes over 10,000 (5 digits), I use 'K' for thousands or 'M' for millions and keep 1 decimal place when the decimal is not 0.
This sometimes causes a loss in precision, but I mitigated this by adding the real quantity when you hover the item.
Also, when reaching such high numbers, I deemed the rounding error acceptable (~0-10%)
