### ISSUE TITLE
Runecrafter data

### ISSUE THREAD

**Issue by Guillaume-Docquier** [Guillaume-Docquier/guillaume-docquier.github.io#9]
Gather all runecrafting recipes.

Put your results in the spreadsheet here: https://docs.google.com/spreadsheets/d/1_VVrggn0nQrVEnUZ43qCUy4MMPXE2T0wzI0N-5nBskQ/edit#gid=1013527178

If you can code, create a pull request. You will find the item definitions in data/items. If you have any question on how it works, just ask.

If you cannot code, gather the information with this format:
- Item name
- Required professions for the item itself (not its components)
- Possible rarities for the item
- List of crafting materials, as seen in the crafting bench (if there's 3 times 1x metal scales, report 3 times 1x metal scales)
- Crafting quantity per craft
- Is the item affected by the rarity of its components
- Is the item customizable (the outcome depends on the materials)

Example 1:
- Item name: Coal
- Professions: Weaponsmith or Armorsmith
- Rarities: white
- Materials: 3x ethereal dust, 3x wood
- Quantity per craft: 5
- Affected by rarity: No
- Customizable: No

Example 2:
- Item name: Metal scales
- Professions: Weaponsmith or Armorsmith
- Rarities: grey, white, green, blue, purple, orange
- Materials: 16x Iron, 10x Ore, 10x Ore, 12x coal
- Quantity per craft: 1
- Affected by rarity: Yes
- Customizable: Yes

**Comment by norsehealer** [comment]
did the text document and/or spreadsheet help with this information?

**Comment by Guillaume-Docquier** [comment]
Haven't checked it yet, I was busy with jewelry and alchemy

**Comment by cbunyard** [comment]
What's the recommended method for handling recipes that have an "or" condition? For example, "Wood or Stone" type recipes.

**Comment by Guillaume-Docquier** [comment]
Since this isn't a very common occurrence, there's no dedicated way to do this. (Yet?)

For now, I was thinking of using the customizations and fake raw materials to support "or".

Basically, you can invent a raw material called WoodOrStone of type Generic Material. Then, you add customizations that will specify the effect of wood and the effect of stone.

If there's no real effect, you can invent one, like "Wooden" and "Stone" just to have placeholders in the dropdowns when you choose it.

If there are specific effects, then list them as you would normally do it.

You'll have to test to see if it works properly, if not we'll do modifications to support it. If you're unable to test, just tell me when it's ready and I'll do it.

If you want an example of this, look for BloodOrWater (or WaterOrBlood?). I did this for jewelcrafting. It's a bit more complex because of how the gems work, but it's the same concept overall.

**Comment by cbunyard** [comment]
That worked, but now we've run upon a new speed bump. Some items require specific customizations from another recipe. E.g., the Discipline: Major recipe in Runemaker requires the Aurelium Metal Bar customization from the Metal Bar recipe in Blacksmithing. Have you considered how you want to approach that?

**Comment by Guillaume-Docquier** [comment]
Hmm that is problematic indeed. I am not sure how to handle this. It will definitely require a change in how the crafting rundown / customization works.
